config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :games, only: %i[show create update] do
    resources :cells, only: %i[update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :game
  has_many :cells
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :cell
end

app/models/cell.rb
class Cell < ApplicationRecord
  enum status: { link: 0, user_played: 1, computer_played: 2, user_cell: 3, boat_hit: 4}
  belongs_to :board
  has_one :boat
end

app/models/game.rb
class Game < ApplicationRecord
  enum progress: {started: 0, in_progress: 1, end: 2}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :games

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController

def update
  @game = Game.find(params[:game_id])
  @computer_board = Board.find_by(game: @game, name: 'computer')
  @cell = Cell.find(params[:id])
  @cell.update(status: 1)
  @game.update(progress: 1)
  computer_move

  winner

  redirect_to game_path(@game)
end

  private

  def computer_move
    @user_board = Board.find_by(game: @game, name: 'you')
    cells = @user_board.cells.where(status: 3)
    @chosen_cell = cells.sample
    @chosen_cell.update(status: 2)
  end

  def winner
    @user_points = @computer_board.cells.where(status: 4).count
    @computer_points = @user_board.cells.where(status: 4).count

    if @user_points == 3
      @game.update(user_won: true, progress: 2)
    elsif @computer_points == 3
      @game.update(progress: 2)
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def show
    @user = current_user
    @game = Game.find(params[:id])

    @user_board = Board.find_by(game: @game, name: 'you')
    @user_table = @user_board.cells.sort_by { |cell| cell.id}

    @computer_board = Board.find_by(game: @game, name: 'computer')
    @computer_table = @computer_board.cells.sort_by { |cell| cell.id}

    @winner = game_winner
  end

  private

  def game_winner
    if @game.user_won == true
      winner = 'You Won'
    else
      winner = 'Computer Won'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    set_up_game
    redirect_to game_path(@game)
  end

  private

  def set_up_game
    @user = current_user
    @game = Game.create!(progress: 0, user: @user)
    create_user_table
    create_computer_table
  end

  def create_user_table
    user_board = Board.create!(name: 'you', game: @game)

    25.times do
      Cell.create!(board: user_board, status: 3)
    end

    cells = Cell.where(board: user_board)
    unique_index = (0..24).to_a.shuffle

    Boat.create!(cell: cells[unique_index.pop])
    Boat.create!(cell: cells[unique_index.pop])
    Boat.create!(cell: cells[unique_index.pop])
  end

  def create_computer_table
    computer_board = Board.create!(name: 'computer', game: @game)

    25.times do
      Cell.create!(board: computer_board, status: 0)
    end

    cells = Cell.where(board: computer_board, status: 0)
    unique_index = (0..24).to_a.shuffle

    Boat.create!(cell: cells[unique_index.pop])
    Boat.create!(cell: cells[unique_index.pop])
    Boat.create!(cell: cells[unique_index.pop])

    cells.shuffle
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.erb
<div class="container w-90 mb-3">
  <div class="text-center">
    <h1 class="mb-3">Battleships</h1>
    <p>Number of games won: <%= Game.where(user_won: true).count %>/<%= Game.where(user: @user).count %></p>
  </div>

  <div class="text-center my-4">
    <% if @game.end? %>
      <h4><%= @winner %></h4>
      <%= link_to 'New Game',:root, class: "btn btn-warning"%>
    <% end %>
  </div>

  <div class="row justify-content-around">
    <div class="col-sm-12 col-md-6 user-grid ">
      <h3 class="text-center mb-3">You</h3>
      <p class="text-center"><%= @user_points %></p>

      <table class="user-table mx-auto">
        <tr>
          <% @user_table[0..4].each do |cell| %>
              <% if cell.boat_hit? %>
                <td class="boat-hit"><% cell.id %></td>
              <% elsif cell.boat.present? && cell.status == 'computer_played'%>
                 <td class="boat-hit"><% cell.id %></td>
                  <% cell.update(status: 4) %>
              <% elsif cell.status == 'computer_played'%>
                <td class="computer-cell"><% cell.id %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="boat"><% cell.boat.cell.id %></td>
                <% else %>
                  <td><% cell.id %></td>
                <% end %>
              <% end %>
          <% end %>
        </tr>
        <tr>
          <% @user_table[5..9].each do |cell| %>
            <% if cell.boat_hit? %>
                <td class="boat-hit"><% cell.id %></td>
              <% elsif cell.boat.present? && cell.status == 'computer_played'%>
                 <td class="boat-hit"><% cell.id %></td>
                  <% cell.update(status: 4) %>
              <% elsif cell.status == 'computer_played'%>
                <td class="computer-cell"><% cell.id %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="boat"><% cell.boat.cell.id %></td>
                <% else %>
                  <td><% cell.id %></td>
                <% end %>
              <% end %>
          <% end %>
        </tr>
        <tr>
          <% @user_table[10..14].each do |cell| %>
            <% if cell.boat_hit? %>
                <td class="boat-hit"><% cell.id %></td>
              <% elsif cell.boat.present? && cell.status == 'computer_played'%>
                 <td class="boat-hit"><% cell.id %></td>
                  <% cell.update(status: 4) %>
              <% elsif cell.status == 'computer_played'%>
                <td class="computer-cell"><% cell.id %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="boat"><% cell.boat.cell.id %></td>
                <% else %>
                  <td><% cell.id %></td>
                <% end %>
              <% end %>
          <% end %>
        </tr>
        <tr>
           <% @user_table[15..19].each do |cell| %>
            <% if cell.boat_hit? %>
                <td class="boat-hit"><% cell.id %></td>
              <% elsif cell.boat.present? && cell.status == 'computer_played'%>
                 <td class="boat-hit"><% cell.id %></td>
                  <% cell.update(status: 4) %>
              <% elsif cell.status == 'computer_played'%>
                <td class="computer-cell"><% cell.id %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="boat"><% cell.boat.cell.id %></td>
                <% else %>
                  <td><% cell.id %></td>
                <% end %>
              <% end %>
          <% end %>
        </tr>
        <tr>
           <% @user_table[20..24].each do |cell| %>
           <% if cell.boat_hit? %>
                <td class="boat-hit"><% cell.id %></td>
              <% elsif cell.boat.present? && cell.status == 'computer_played'%>
                 <td class="boat-hit"><% cell.id %></td>
                  <% cell.update(status: 4) %>
              <% elsif cell.status == 'computer_played'%>
                <td class="computer-cell"><% cell.id %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="boat"><% cell.boat.cell.id %></td>
                <% else %>
                  <td><% cell.id %></td>
                <% end %>
              <% end %>
          <% end %>
        </tr>
      </table>
    </div>

<%# ---------------------------------------------COMPUTER------------------------------------------------ %>
    <div class="col-sm-12 col-md-6 computer-grid">
      <h3 class="text-center">Computer</h3>
       <p class="text-center"><%= @computer_points %></p>

      <table class="computer-table mx-auto">
         <tr>
          <% @computer_table[0..4].each do |cell| %>
            <% if cell.status == 'link' && @game.end? == false%>
              <td><%= link_to 'click', game_cell_path(@game, cell), data: {turbo_method: :patch}, class: 'link' %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="computer-boat"><% cell.id %></td>
                  <% cell.update(status: 4) %>
                <% else %>
                  <% if @game.end? && cell.user_played? == false %>
                      <td class='link-inactive'><% cell.id %></td>
                    <% else %>
                      <td class="computer-cell"><% cell.id %></td>
                  <% end %>
                <% end %>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <% @computer_table[5..9].each do |cell| %>
             <% if cell.status == 'link' && @game.end? == false %>
              <td><%= link_to 'click', game_cell_path(@game, cell), data: {turbo_method: :patch}, class: 'link' %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="computer-boat"><% cell.id %></td>
                  <% cell.update(status: 4) %>
                <% else %>
                  <% if @game.end? && cell.user_played? == false %>
                      <td class='link-inactive'><% cell.id %></td>
                    <% else %>
                      <td class="computer-cell"><% cell.id %></td>
                  <% end %>
                <% end %>
            <% end %>
          <% end %>
        </tr>
        <tr>
          <% @computer_table[10..14].each do |cell| %>
             <% if cell.status == 'link' && @game.end? == false %>
              <td><%= link_to 'click', game_cell_path(@game, cell), data: {turbo_method: :patch}, class: 'link' %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="computer-boat"><% cell.id %></td>
                  <% cell.update(status: 4) %>
                <% else %>
                  <% if @game.end? && cell.user_played? == false %>
                      <td class='link-inactive'><% cell.id %></td>
                    <% else %>
                      <td class="computer-cell"><% cell.id %></td>
                  <% end %>
                <% end %>
            <% end %>
          <% end %>
        </tr>
        <tr>
           <% @computer_table[15..19].each do |cell| %>
            <% if cell.status == 'link' && @game.end? == false %>
              <td><%= link_to 'click', game_cell_path(@game, cell), data: {turbo_method: :patch}, class: 'link' %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="computer-boat"><% cell.id %></td>
                  <% cell.update(status: 4) %>
                <% else %>
                  <% if @game.end? && cell.user_played? == false %>
                      <td class='link-inactive'><% cell.id %></td>
                    <% else %>
                      <td class="computer-cell"><% cell.id %></td>
                  <% end %>
                <% end %>
            <% end %>
          <% end %>
        </tr>
        <tr>
           <% @computer_table[20..24].each do |cell| %>
            <% if cell.status == 'link' && @game.end? == false %>
              <td><%= link_to 'click', game_cell_path(@game, cell), data: {turbo_method: :patch}, class: 'link' %></td>
              <% else %>
                <% if cell.boat.present? %>
                  <td class="computer-boat"><% cell.id %></td>
                  <% cell.update(status: 4) %>
                <% else %>
                  <% if @game.end? && cell.user_played? == false %>
                      <td class='link-inactive'><% cell.id %></td>
                    <% else %>
                      <td class="computer-cell"><% cell.id %></td>
                  <% end %>
                <% end %>
            <% end %>
          <% end %>
        </tr>
      </table>
    </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArmiBattleship</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>